export const RecordsActionTypes = {
	SET_PEST_DETECTION: 'SET_PEST_DETECTION',
	SET_FULL_INSPECTION: 'SET_FULL_INSPECTION',
	REMOVE_DETECTION: 'REMOVE_DETECTION',
	ADD_HARVEST_RECORD: 'ADD_HARVEST_RECORD',
	ADD_FERTILIZATION_RECORD: 'ADD_FERTILIZATION_RECORD',
	SET_PRODUCT_APPLICATION: 'SET_PRODUCT_APPLICATION',
	CLEAR_PRODUCT_APPLICATION: 'CLEAR_PRODUCT_APPLICATION',
	ADD_APPLICATION_RECORD: 'ADD_APPLICATION_RECORD',
	SET_INPUT_SEARCH: 'SET_INPUT_SEARCH',
	CLEAR_INPUT_SEARCH: 'CLEAR_INPUT_SEARCH'
}