export const RecordsActionTypes = {
	SET_PEST_DETECTION: 'SET_PEST_DETECTION',
	SET_FULL_INSPECTION: 'SET_FULL_INSPECTION',
	REMOVE_DETECTION: 'REMOVE_DETECTION',
	ADD_HARVEST_RECORD: 'ADD_HARVEST_RECORD',
	ADD_FERTILIZATION_RECORD: 'ADD_FERTILIZATION_RECORD',
	ADD_APPLICATION_RECORD: 'ADD_APPLICATION_RECORD'
}