export const RanchActionTypes = {
	SET_CURRENT_RANCH: 'SET_CURRENT_RANCH',
	SET_ALL_RANCHES: 'SET_ALL_RANCHES',
	SET_CURRENT_SECTOR: 'SET_CURRENT_SECTOR',
	SET_ALL_SECTORS: 'SET_ALL_SECTORS',
	CLEAR_RANCHES: 'CLEAR_RANCHES',
	SET_SELECTED_SECTOR: 'SET_SELECTED_SECTOR',
	REMOVE_SELECTED_SECTOR: 'REMOVE_SELECTED_SECTOR',
	CLEAR_SELECTED_SECTORS: 'CLEAR_SELECTED_SECTORS'
}