const organisms = {
    'pests': [
        'Acaro blanco',
        'Acaro de dos manchas',
        'Acaro de las Yemas',
        'Acaro del Berry Rojo',
        'Acaros',
        'Afidos',
        'Aphidos',
        'Araña',
        'Araña Ciclamina',
        'Araña de dos manchas',
        'Araña de dos puntos',
        'Araña Roja',
        'Babosa (Molusco)',
        'Babosas y caracoles',
        'Barrenador Europeo',
        'Chapulin',
        'Chicharrita (salta hojas)',
        'Chicharritas',
        'Chinche',
        'Chinche de las semillas',
        'Chinche Lygus',
        'Cochinilla Acanalada',
        'Defoliadores',
        'Diabrótica',
        'Drosophila suzukii',
        'Escama',
        'Gallina Ciega',
        'Gallina ciega (larvas)',
        'Gusano',
        'Gusano  barrenador de corona',
        'Gusano Cogollero',
        'Gusano Cortador',
        'Gusano de alambre',
        'Gusano de la fruta',
        'Gusano del Fruto',
        'Gusano del tallo',
        'Gusano Enrrollador',
        'Gusano Falso medidor',
        'Gusano Soldado',
        'Gusano Trozador',
        'Hormiga Fuego',
        'Lygus',
        'Minador',
        'Minador de la hoja',
        'Minadores',
        'Mosca Blanca',
        'Mosca de alas manchadas',
        'Mosca de los brotes',
        'Mosca del vinagre',
        'Mosca del vinagre de las alas manchadas',
        'Mosquita blanca',
        'Nematodo agallador',
        'Ninfa de mosca blanca',
        'Picudo de la flor de fresa',
        'Piojo harinoso',
        'Pulgon',
        'Pulgon (afidos)',
        'Pythium',
        'Trips',
        'Trips del Cogollo'
    ],
    'diseases': [
        'Agalla de la corona',
        'Alternaria',
        'Antracnocsis',
        'Botrytis',
        'Cenicilla',
        'Cenicilla polvorienta',
        'Cenicilla vellosa',
        'Colletotrichum',
        'Damping off',
        'Didimela',
        'Fusarium',
        'Mancha agular de la hoja',
        'Mancha Angular',
        'Mancha Angular (Xanthomonas)',
        'Mancha Bacteriana',
        'Mancha de la hoja',
        'Mancha de la hoja y tallo',
        'Mancha foliar',
        'Mancha o peca de la hoja',
        'Marchitez',
        'Mildiu',
        'Mildiu Polvorienta ',
        'Mildiu Velloso',
        'Moho',
        'Moho blanco ',
        'Moho Gris',
        'Mummy berry',
        'Oídio',
        'Paratrioza',
        'Peca de la hoja',
        'Peca o Mancha de la hoja',
        'Phoma de la caña',
        'Phomopsis',
        'Phytophthora infestans',
        'Pseudoperonospora cubensis',
        'Pudricion',
        'Pudrición café',
        'Pudricion de la corona',
        'Pudricion de la Raiz',
        'Pudricion de la raiz y cuello',
        'Pudricion de raiz',
        'Pudricion de raiz y corona',
        'Pudricion del fruto',
        'Pudrición gris del fruto',
        'Quemadura de la hoja',
        'Rhizoctonia',
        'Roya',
        'Roya de la frambuesa',
        'Tizon',
        'Tizon de Yemas',
        'Tizon del Tallo',
        'Verticillum',
        'Viruela de la fresa'
    ], 
    'beneficials': [
        'Catarina',
        'Crisopas',
        'Chinche Asesina',
        'Chinche Pirata',
        'Escarabajo Colops',
        'Mosca Sirfida',
        'Mantis Religiosa',
        'Avispas Parasitarias'
    ],
    weeds: [
        'Aceitilla',
        'Borreguilla',
        'Cadillo',
        'Coquillo (Cyperus rotundus)',
        'Corehuela',
        'Girasol',
        'Golondrina',
        'Grama (Hoja Angosta)',
        'Gramineas',
        'Hoja Ancha',
        'Hoja Angosta',
        'Johnsongrass (Hoja Angosta)',
        'Maleza',
        'Quelite Bledo (Amaranthus hybridus)',
        'Zacate Gramma Cynodon dactylon',
        'Zacate Orquetilla',
        'Zacate pata de gallina',
        'Zacate Gramma'
    ]
}

export default organisms;